include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print: false
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_empty_else
    - avoid_relative_lib_imports
    - directives_ordering
    - unnecessary_brace_in_string_interps
    - prefer_single_quotes

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    unused_import: warning
    invalid_assignment: warning
    missing_return: error
    dead_code: warning