name: tarot_app
description: Application mobile pour jouer au Tarot
publish_to: 'none' # Pour ne pas publier sur pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Widgets et UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  
  # État et navigation
  provider: ^6.0.5
  go_router: ^9.0.0
  
  # Stockage local
  shared_preferences: ^2.1.1
  path_provider: ^2.0.15
  
  # Réseau et API
  http: ^1.0.0
  connectivity_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting et formatting
  flutter_lints: ^2.0.0
  
  # Tests
  mockito: ^5.4.0
  test: ^1.24.1

# Configuration Flutter
flutter:
  uses-material-design: true
  
  # Décommentez pour ajouter des assets
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # Décommentez pour ajouter des polices
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700