version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend/app:/app/app
      - ../backend/tarot_logic:/app/tarot_logic
    restart: unless-stopped
    environment:
      - DEBUG=1
