name: Tarot App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend_tests:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend
    
    strategy:
      matrix:
        python-version: [3.9]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: curl -sSf https://install.python-poetry.org | python3 - && pip install uv
    
    - name: Install dependencies
      run: |
        uv venv .venv
        source .venv/bin/activate
        uv pip install -e .
        uv pip install -e ".[dev]"
    
    - name: Lint with ruff
      run: |
        source .venv/bin/activate
        ruff check .
    
    - name: Format check with ruff
      run: |
        source .venv/bin/activate
        ruff format . --check
    
    - name: Test with pytest
      run: |
        source .venv/bin/activate
        pytest
  
  flutter_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.x'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Analyze project source
      run: flutter analyze
    
    - name: Run tests
      run: flutter test
